# Wir legen fest, dass wir unser Programm mit Python in der Version 3.7 ausführen möchten.
image: "python:3.7"

# Wir stellen sicher, dass unsere Umgebung für die Ausführung unseres Programms bereit ist.
before_script:
  - python --version
  - pip --version
 # - pip install --no-cache-dir tensorflow
  - pip install -r requirements.txt

# Wir haben zwei Stages: Das Linting und das Testing
stages:
  - Lint
  - Test

# Wir prüfen, ob der eingecheckte Code auch den PEP-8-Richtlinien entspricht.
# Scores >= 8.0/10.0 erlaubt
linting:
  stage: Lint
  script:
    - pylint *.py #--evaluation= min(10.0, 12.0 - ((float(5 * error + warning + refactor + convention) / statement) * 10))

# Wir lassen alle Tests laufen. Die Dateien dafür beginnen mit "test". 
unittest:
  stage: Test
  script:
    - python3 Tests/test*.py
