name: "model_deep"

# Trainable params: 53,745,869
model:
    resnet_depth: 15
    training:
        learning_rate: 1.e-3
        batch_size: 64
    logging:
        save_model_every: 5
        log_metrics_every: 1
        log_mlflow: True
        load_from_mlflow: True
        mlflow_model_version: 0
        save_local: True
        save_mlflow: True
    residual_block:
        layers: 3
        num_filters: 128
        filter_size: 3

