name: "model_wide"

# Trainable params: 67,393,613
model:
    resnet_depth: 11
    training:
        learning_rate: 1.e-3
        batch_size: 64
    logging:
        save_model_every: 5
        log_metrics_every: 1
        log_mlflow: True
        load_from_mlflow: True
        mlflow_model_version: 0
        save_local: True
        save_mlflow: True
    residual_block:
        layers: 2
        num_filters: 192
        filter_size: 3

