name: "model_deep"

player:
    heat: 1
    exploration: 1
    rollout_payoffs:
        white:
            white_wins: 1
            black_wins: -1
            draw: 0
            draw_by_rep: -1
            draw_by_stale_mate: 0
            draw_by_two_wins: 0
        black:
            white_wins: -1
            black_wins: 1
            draw: 0
            draw_by_rep: -1
            draw_by_stale_mate: 0
            draw_by_two_wins: 0


# Trainable params:
model:
    resnet_depth: 15
    logging:
        save_model_every: 20
        log_metrics_every: 5
        log_mlflow: True
        load_from_mlflow: False
        mlflow_model_version: 0
        save_local: True
        save_mlflow: True
    training:
        batch_size: 64
    residual_block:
        layers: 2
        num_filters: 128
        filter_size: 3
    policy_head:
        residual_layer:
            num_filters: 4
    value_head:
        residual_layer:
            num_filters: 4
        dense_layer:
            num_filters: 256
