name: "SportySparrow"

#player parameters
player:
    heat: 1000
    exploration: 1000
    rollout_payoffs:
        white:
            white_wins: 100
            black_wins: -100
            draw: 0
            draw_by_rep: 0
            draw_by_stale_mate: 0
            draw_by_two_wins: 0
        black:
            white_wins: -100
            black_wins: 100
            draw: 0
            draw_by_rep: 0
            draw_by_stale_mate: 0
            draw_by_two_wins: 0

# Trainable params: 6,845,459
model:
    resnet_depth: 7
    logging:
        save_model_every: 1
        log_metrics_every: 1
        log_mlflow: False
        load_from_mlflow: False
        mlflow_model_version: 0
        save_local: True
        save_mlflow: False
    training:
        batch_size: 64
        learning_rate: 3.e-4
    residual_block:
        layers: 2
        num_filters: 128
        filter_size: 5
    policy_head:
        residual_layer:
            num_filters: 4
    value_head:
        residual_layer:
            num_filters: 2
        dense_layer:
            num_filters: 128
