name: "TestingTortoise2"

# Trainable params: 6,845,459
model:
    resnet_depth: 7
    logging:
        save_model_every: 1
        log_metrics_every: 1
        log_mlflow: False
        load_from_mlflow: False
        mlflow_model_version: 0
        save_local: True
        save_mlflow: False
    training:
        batch_size: 64
    residual_block:
        layers: 2
        num_filters: 128
        filter_size: 5
    policy_head:
        residual_layer:
            num_filters: 4
    value_head:
        residual_layer:
            num_filters: 2
        dense_layer:
            num_filters: 128
